/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author hafiz
 */
public class DataPasien extends javax.swing.JFrame {
public Statement st;
public ResultSet rs;
public DefaultTableModel tabModel;
Connection cn = koneksi.Koneksi.Koneksi();

 public void judul() {
 Object[] judul = {
 "Nomor Rekam Medis", "Nama Lengkap", "Tanggal Lahir", "JK", "Golongan Darah", "Alamat", "No telp" 
 };
 tabModel = new DefaultTableModel(null, judul);
 tablePasien.setModel(tabModel);
}
 
    /**
     * Creates new form DataPasien
     */
    public DataPasien() {
        initComponents();
        judul ();
        tampilData();
        btnHapus.setEnabled(false);
        btnEdit.setEnabled(false);
    }
private void tampilData() {
    try {
        st = cn.createStatement();
        tabModel.getDataVector().removeAllElements();
        tabModel.fireTableDataChanged();
        rs = st.executeQuery("SELECT * FROM data_pasien");
        while (rs.next()) {
            Object[] data = {
                rs.getString("nomor_rekam_medis"),
                rs.getString("nama_lengkap"),
                rs.getString("tanggal_lahir"),
                rs.getString("jk"),
                rs.getString("goldar"),
                rs.getString("alamat"),  
                rs.getString("no_telp")
            };
            tabModel.addRow(data);
        }
    } catch(Exception e) {
        e.printStackTrace();
    }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputNomorRekamMedis = new javax.swing.JTextField();
        InputTMT = new javax.swing.JTextField();
        InputTelp = new javax.swing.JTextField();
        InputAlamat = new javax.swing.JTextField();
        InputJK = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        InputGolDar = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePasien = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        InputNama = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InputNomorRekamMedis.setText("jTextField1");
        InputNomorRekamMedis.setName("InputNomorRekamMedis"); // NOI18N
        InputNomorRekamMedis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNomorRekamMedisActionPerformed(evt);
            }
        });

        InputTMT.setText("31-12-3001");
        InputTMT.setName("InputTMT"); // NOI18N
        InputTMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTMTActionPerformed(evt);
            }
        });

        InputTelp.setText("jTextField3");
        InputTelp.setName("InputTelp"); // NOI18N
        InputTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTelpActionPerformed(evt);
            }
        });

        InputAlamat.setText("jTextField4");
        InputAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputAlamatActionPerformed(evt);
            }
        });

        InputJK.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki-Laki", "Perempuan" }));
        InputJK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputJKActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setText("Form Data Pasien");

        jLabel2.setText("Nama Lengkap          ");
        jLabel2.setMaximumSize(new java.awt.Dimension(103, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(103, 14));

        jLabel3.setText("Alamat                        ");

        jLabel4.setText("Tanggal Lahir             ");

        jLabel5.setText("Nomor Telepon          ");

        jLabel6.setText("Jenis Kelamin             ");

        InputGolDar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "AB", "O" }));
        InputGolDar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputGolDarActionPerformed(evt);
            }
        });

        jLabel7.setText("Golongan Darah         ");

        tablePasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePasien);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jButton5.setText("Kembali");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        InputNama.setText("jTextField2");
        InputNama.setName("InputTMT"); // NOI18N
        InputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNamaActionPerformed(evt);
            }
        });

        jLabel8.setText("Nomor Rekam Medis ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputNomorRekamMedis, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(InputNama, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(InputTMT, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(InputTelp, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(InputJK, javax.swing.GroupLayout.Alignment.LEADING, 0, 145, Short.MAX_VALUE)
                            .addComponent(InputGolDar, javax.swing.GroupLayout.Alignment.LEADING, 0, 145, Short.MAX_VALUE)
                            .addComponent(InputAlamat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton5)
                .addGap(135, 135, 135)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton5))
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputNomorRekamMedis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputTMT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InputGolDar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(InputAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnEdit))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReset)
                            .addComponent(btnHapus)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        btnTambah.setEnabled(true);
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void InputNomorRekamMedisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNomorRekamMedisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNomorRekamMedisActionPerformed

    private void InputTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputTelpActionPerformed

    private void InputAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputAlamatActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    try {
        String rekamMedis = InputNomorRekamMedis.getText();
        String nama = InputNama.getText();
        String tglLahir = InputTMT.getText();
        String jk = InputJK.getSelectedItem().toString();
        String golDar = InputGolDar.getSelectedItem().toString();
        String alamat = InputAlamat.getText();
        String noTelp = InputTelp.getText();
        // Error handling
        if (rekamMedis.length() > 11) {
            JOptionPane.showMessageDialog(null, "Nomor Rekam Medis maksimal 11 karakter!");
            return;
        }
        if (nama.length() > 100) {
            JOptionPane.showMessageDialog(null, "Nama maksimal 100 karakter!");
            return;
        }
        if (tglLahir.length() > 20) {
            JOptionPane.showMessageDialog(null, "Tanggal Lahir maksimal 20 karakter!");
            return;
        }
        if (jk.length() > 16) {
            JOptionPane.showMessageDialog(null, "Jenis Kelamin maksimal 16 karakter!");
            return;
        }
        if (golDar.length() > 20) {
            JOptionPane.showMessageDialog(null, "Golongan Darah maksimal 20 karakter!");
            return;
        }
        if (!noTelp.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "No Telp hanya boleh angka!");
            return;
        }
        if (noTelp.length() > 13) {
            JOptionPane.showMessageDialog(null, "No Telp maksimal 13 digit!");
            return;
        }

//}

        Pasien pasien = new Pasien(rekamMedis, nama, tglLahir, jk, golDar, alamat, noTelp);

        st = cn.createStatement();
        st.executeUpdate("INSERT INTO data_pasien VALUES('" 
            + pasien.getNomorRekamMedis() + "','" 
            + pasien.getNama() + "','" 
            + pasien.getTanggalLahir() + "','" 
            + pasien.getJenisKelamin() + "','" 
            + pasien.getGolonganDarah() + "','" 
            + pasien.getAlamat() + "','" 
            + pasien.getNoTelp() + "')");

        tampilData();
        JOptionPane.showMessageDialog(null, "Simpan Berhasil");
        reset();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menyimpan data.");
    }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void InputTMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTMTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputTMTActionPerformed

    private void InputJKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputJKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputJKActionPerformed

    private void InputGolDarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputGolDarActionPerformed
//InputGolDar.addItem("A+");
//InputGolDar.addItem("A-");
//InputGolDar.addItem("B+");
//InputGolDar.addItem("B-");
//InputGolDar.addItem("AB");
//InputGolDar.addItem("O+");
//InputGolDar.addItem("O-");
    }//GEN-LAST:event_InputGolDarActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
     try {
        String rekamMedis = InputNomorRekamMedis.getText();
        String nama = InputNama.getText();
        String tglLahir = InputTMT.getText();
        String jk = InputJK.getSelectedItem().toString();
        String golDar = InputGolDar.getSelectedItem().toString();
        String alamat = InputAlamat.getText();
        String noTelp = InputTelp.getText();
//Error Handling
        if (rekamMedis.length() > 11) {
            JOptionPane.showMessageDialog(null, "Nomor Rekam Medis maksimal 11 karakter!");
            return;
        }
        if (nama.length() > 100) {
            JOptionPane.showMessageDialog(null, "Nama maksimal 100 karakter!");
            return;
        }
        if (tglLahir.length() > 10) {
            JOptionPane.showMessageDialog(null, "Tanggal Lahir maksimal 20 karakter!");
            return;
        }
        if (jk.length() > 16) {
            JOptionPane.showMessageDialog(null, "Jenis Kelamin maksimal 16 karakter!");
            return;
        }
        if (golDar.length() > 20) {
            JOptionPane.showMessageDialog(null, "Golongan Darah maksimal 20 karakter!");
            return;
        }
        if (!noTelp.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "No Telp hanya boleh angka!");
            return;
        }
        if (noTelp.length() > 13) {
            JOptionPane.showMessageDialog(null, "No Telp maksimal 13 digit!");
            return;
        }

        Pasien pasien = new Pasien(rekamMedis, nama, tglLahir, jk, golDar, alamat, noTelp);

        st = cn.createStatement();
        st.executeUpdate("UPDATE data_pasien SET "
            + "nama_lengkap='" + pasien.getNama() + "', "
            + "tanggal_lahir='" + pasien.getTanggalLahir() + "', "
            + "jk='" + pasien.getJenisKelamin() + "', "
            + "goldar='" + pasien.getGolonganDarah() + "', "
            + "alamat='" + pasien.getAlamat() + "', "
            + "no_telp='" + pasien.getNoTelp() + "' "
            + "WHERE nomor_rekam_medis='" + pasien.getNomorRekamMedis() + "'");

        tampilData();
        JOptionPane.showMessageDialog(null, "Update Berhasil");
        reset();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mengedit data.");
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    try {
        int jawab = JOptionPane.showConfirmDialog(this, "Hapus Data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (jawab == JOptionPane.YES_OPTION) {
            st = cn.createStatement();
            st.executeUpdate("DELETE FROM data_pasien WHERE nomor_rekam_medis='"
                + InputNomorRekamMedis.getText() + "'");
            tampilData();
            JOptionPane.showMessageDialog(null, "Hapus Berhasil");
            reset();
            //        tambah error handling buat Telp,Nomor Rekam,dll
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
      
    }//GEN-LAST:event_btnHapusActionPerformed

    private void InputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNamaActionPerformed

    private void tablePasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePasienMouseClicked
        int row = tablePasien.getSelectedRow();
InputNomorRekamMedis.setText(tablePasien.getValueAt(row, 0).toString());
InputNama.setText(tablePasien.getValueAt(row, 1).toString());
InputTMT.setText(tablePasien.getValueAt(row, 2).toString());
InputJK.setSelectedItem(tablePasien.getValueAt(row, 3).toString());
InputGolDar.setSelectedItem(tablePasien.getValueAt(row, 4).toString());
InputAlamat.setText(tablePasien.getValueAt(row, 5).toString());
InputTelp.setText(tablePasien.getValueAt(row, 6).toString());
 btnTambah.setEnabled(false);
 btnEdit.setEnabled(true);
 btnHapus.setEnabled(true);
    }//GEN-LAST:event_tablePasienMouseClicked
public void reset() {
 InputNomorRekamMedis.setText("");
 InputNama.setText("");
 InputJK.setSelectedItem("");
 InputGolDar.setSelectedItem("");
 InputTMT.setText("");
 InputTelp.setText("");
 InputAlamat.setText("");
}



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputAlamat;
    private javax.swing.JComboBox InputGolDar;
    private javax.swing.JComboBox InputJK;
    private javax.swing.JTextField InputNama;
    private javax.swing.JTextField InputNomorRekamMedis;
    private javax.swing.JTextField InputTMT;
    private javax.swing.JTextField InputTelp;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePasien;
    // End of variables declaration//GEN-END:variables
}
